# Generated by Django 6.0.5 on 2026-05-07 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_number', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('gotra', models.CharField(max_length=100)),
                ('password', models.CharField(default='1234', max_length=50)),
                ('marital_status', models.CharField(default='unmarried', max_length=20)),
                ('spouse_name', models.CharField(blank=True, max_length=100, null=True)),
                ('spouse_phone', models.CharField(blank=True, max_length=10, null=True)),
                ('detailed_address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.area')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('main_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='directory.member')),
            ],
        ),
    ]
