# Generated by Django 6.0.5 on 2026-05-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_member_head_name_member_is_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
