# Generated by Django 6.0.5 on 2026-05-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_familymember_dob_member_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='marital_status',
            field=models.CharField(default='unmarried', max_length=20),
        ),
        migrations.AddField(
            model_name='familymember',
            name='spouse_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
