# Generated by Django 6.0.5 on 2026-05-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_familymember_marital_status_familymember_spouse_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='spouse_dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='spouse_dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
