# Generated by Django 6.0.5 on 2026-05-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_familymember_spouse_dob_member_spouse_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='spouse_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='spouse_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
