# Generated by Django 6.0.5 on 2026-05-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0007_member_head_dob_member_head_marital_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='pin',
            field=models.CharField(default='0000', max_length=4),
        ),
    ]
