# Generated by Django 6.0.5 on 2026-05-09 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0008_member_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='password',
        ),
    ]
