# Generated by Django 6.0.5 on 2026-05-10 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0009_remove_member_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familymember',
            old_name='main_member',
            new_name='member',
        ),
    ]
