# Generated by Django 6.0.5 on 2026-05-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0010_rename_main_member_familymember_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familymember',
            name='spouse_dob',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='spouse_phone',
        ),
        migrations.AlterField(
            model_name='familymember',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
