# Generated by Django 6.0.5 on 2026-05-11 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0011_remove_familymember_spouse_dob_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
