# Generated by Django 6.0.5 on 2026-05-16 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0012_remove_member_created_at_alter_area_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='spouse_dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='spouse_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
