# Generated by Django 6.0.5 on 2026-05-17 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0013_familymember_spouse_dob_familymember_spouse_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='registration_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
