# Generated by Django 6.0.5 on 2026-05-20 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0014_member_registration_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='is_out_of_station',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='familymember',
            name='occupation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
