# Generated by Django 6.0.5 on 2026-05-20 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0015_familymember_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='head_occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='spouse_occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
