# Generated by Django 6.0.5 on 2026-05-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0016_member_head_occupation_member_spouse_occupation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='spouse_occupation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
